POST http://localhost:8080/
Content-Type: application/json

{
  "id": 1,
  "title": "obsah",
  "content": "obsah",
  "description": "obsah"
}

###
POST http://localhost:8080/
Content-Type: application/json

{
  "id": 2,
  "title": "obsah"
}